server:
  port: 8083
spring:
  application:
    name: micro-sso
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 960823
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=GMT%2b8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: true
    register-with-eureka: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml