server:
  port: 9090
spring:
  application:
    name: manager-server
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: true
    register-with-eureka: false
ribbon:
  ReadTimeout: 5000