server:
  port: 8080
spring:
  application:
    name: city-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useSSL=true&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 960823
  rabbitmq:
    host: mystar.cool
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动确认消息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: true
    register-with-eureka: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl