server:
  port: 8082
spring:
  application:
    name: micro-search
  elasticsearch:
    rest:
      uris: http://mystar.cool:9200
  rabbitmq:
    host: mystar.cool
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: true
    register-with-eureka: true
